### ISSUE TITLE
CrashServer use /rtp BetterRTP 2.11.2 1.16.1

### ISSUE THREAD

**Issue by iLiDanMoon** [SuperRonanCraft/BetterRTP#38] opened 2020-08-07 06:53 UTC
[crash.txt](https://github.com/SuperRonanCraft/BetterRTP/files/5039796/crash.txt)

**Comment by iLiDanMoon** [comment] 2020-08-07 06:54
[09:27:00] [Server thread/INFO]: garik4 issued server command: /rtp
[09:27:13] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-133 (MC: 1.16.1) ---
[09:27:13] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[09:27:13] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:13] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[09:27:13] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:13] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[09:27:13] [Paper Watchdog Thread/ERROR]: 	PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[09:27:13] [Paper Watchdog Thread/ERROR]: 	Stack:
[09:27:13] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.sleep(Native Method)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTPTeleport.loadChunks(RTPTeleport.java:55)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTPTeleport.sendPlayer(RTPTeleport.java:21)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTP.tp(RTP.java:166)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.Delay.lambda$run$0(Delay.java:93)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.Delay$$Lambda$6385/0x0000000841a1dc40.run(Unknown Source)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3005/0x000000084082c440.run(Unknown Source)
[09:27:13] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
[09:27:13] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:13] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[09:27:13] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:18] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-133 (MC: 1.16.1) ---
[09:27:18] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
[09:27:18] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:18] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[09:27:18] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:18] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[09:27:18] [Paper Watchdog Thread/ERROR]: 	PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[09:27:18] [Paper Watchdog Thread/ERROR]: 	Stack:
[09:27:18] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.sleep(Native Method)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTPTeleport.loadChunks(RTPTeleport.java:55)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTPTeleport.sendPlayer(RTPTeleport.java:21)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.RTP.tp(RTP.java:166)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.Delay.lambda$run$0(Delay.java:93)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		me.SuperRonanCraft.BetterRTP.player.Delay$$Lambda$6385/0x0000000841a1dc40.run(Unknown Source)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3005/0x000000084082c440.run(Unknown Source)
[09:27:18] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
[09:27:18] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:27:18] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[09:27:18] [Paper Watchdog Thread/ERROR]: ------------------------------

**Comment by christaylor201** [comment] 2020-08-07 07:38
I wanted to report this issue, too. I think the cause of this is the `Thread.sleep()` method being called in the main thread, see [the code](https://github.com/SuperRonanCraft/BetterRTP/blob/060361c6e79f154985a994c6d8790a0711fb19fc/src/main/java/me/SuperRonanCraft/BetterRTP/player/RTPTeleport.java#L59).

**Comment by SuperRonanCraft** [comment] 2020-08-07 12:14
Yeah, I was made aware of this yesterday. It has to do that Delays calling the rtp code on the main thread, unlike when you bypass them it runs async. I will bw getting a hot fix for this today!

**Comment by SuperRonanCraft** [comment] 2020-08-07 13:37
Just posted an [update](https://www.spigotmc.org/resources/betterrtp.36081/update?update=353323), let me know if you have any other issues!

**Closed by SuperRonanCraft** 2020-08-07 13:37 UTC
Labels: Bug, Fixed - Pending Release
